class Settings:
    DEBUG = False
    MULTIPROCESS = True
    NUM_PROCESSES = 8
    DIMENSIONS_2 = 2
    DIMENSIONS_10 = 10
    DIMENSIONS_30 = 30
    COST_FUNCTION_EVALUATION_FACTOR = 2000
    LOWER_BOUND = -100
    UPPER_BOUND = 100
